name: Sync labels
on:
  push:
    branches:
      - master
    paths:
      - .github/config/labels.yml
      - .github/workflows/label-syncer.yml
jobs:
  sync-labels:
    name: 🏷️ sync labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/config/labels.yml
          prune: true
